// This file is autogenerated. Changes will be overwritten.
#include "UVLADIE3JM/moc_AboutDialog.cpp"
#include "UVLADIE3JM/moc_Application.cpp"
#include "UVLADIE3JM/moc_QuoteWidget.cpp"
#include "UVLADIE3JM/moc_TrayIcon.cpp"
