name: SwiftLint
on:
  pull_request:
    paths:
      - '**/*.swift'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  SwiftLint:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Verify Swift Toolchain
        run: swift --version

      - name: Install SwiftLint
        run: |
          if ! swiftlint --version; then
            brew install swiftlint
          fi

      - name: Run SwiftLint
        run: swiftlint
