name: SwiftLint
on:
  pull_request:
    paths:
      - '**/*.swift'

jobs:
  SwiftLint:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verify Swift Toolchain
        run: swift --version

      - name: Install SwiftLint
        run: |
          if ! swiftlint --version; then
            brew install swiftlint
          fi

      - name: Run SwiftLint
        run: swiftlint
